# Docs at https://github.com/bitnami/charts/blob/master/bitnami/nginx/values.yaml
#
image:
  repository: aypx/gitops-poc-app-2
  tag: latest

# NGINX Service properties
#
service:
  # Service type
  type: ClusterIP
  # HTTP Port
  port: 80

# Configure the ingress resource that allows you to access the
# Nginx installation. Set up the URL
# ref: http://kubernetes.io/docs/user-guide/ingress/
#
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  # When the ingress is enabled, a host pointing to this will be created
  hostname: app2.local
  path: /
  pathType: Prefix

## Prometheus Exporter / Metrics
##
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    ## Namespace in which Prometheus is running
    namespace: kube-prometheus-stack
