apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopoc-app2-nginx
  namespace: gopoc-app2
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: aypx/gitops-poc-app-2:main-72c0ee0-1620138040 # {"$imagepolicy": "flux-system:app-application-2"}
