---
# Source: nginx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopoc-app2-nginx
  namespace: gopoc-app2
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: docker.io/aypx/gitops-poc-app-2:main
