---
# Source: nginx/templates/server-block-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gopoc-app2-nginx-server-block
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-8.9.0
    app.kubernetes.io/instance: gopoc-app2
    app.kubernetes.io/managed-by: Helm
data:
  server-blocks-paths.conf: |-
    include  "/opt/bitnami/nginx/conf/server_blocks/ldap/*.conf";
    include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf";
